#!/bin/zsh
xrandr --output DP-1 --off --output HDMI-1 --primary --mode 1920x1080 --pos 1366x0 --rotate normal --output eDP-1 --mode 1366x768 --pos 0x312 --rotate normal --output HDMI-2 --off
pkill polybar
MONITOR=eDP-1 polybar --reload example &
MONITOR=HDMI-1 polybar --reload example &
setxkbmap -layout us -variant altgr-intl ; xmodmap ~/.Xmodmap

for i in 6 7 8 9 10
do
  i3-msg workspace $i, move workspace to output HDMI-1
done

for i in 1 2 3 4 5
do
  i3-msg workspace $i, move workspace to output eDP-1
done

i3-msg workspace 1
i3-msg workspace 10
