#!/bin/sh
xrandr --output DP-1 --off --output HDMI-1 --off --output eDP-1 --primary --mode 1366x768 --rotate normal --output HDMI-2 --off
pkill polybar
MONITOR=eDP-1 polybar --reload example &
setxkbmap -layout us -variant altgr-intl ; xmodmap ~/.Xmodmap

for i in 1 2 3 4 5 6 7 8 9 10
do
  i3-msg workspace $i, move workspace to output eDP-1
done

i3-msg workspace 10
