#!/bin/sh

set -eu

usdprice=$(w3m preciodolarblue.com.ar | grep Compra -A 1 |tail -n 1|cut -f 1 -d ' ')
baseFee=$(curl 'https://api.ethgasstation.info/api/fee-estimate'|jq ".baseFee") 

echo "Ξ ${baseFee}| USD ${usdprice}" > ~/.config/i3blocks/asyncblocks

pkill -SIGRTMIN+12 dwmblocks
