#!/bin/zsh
xrandr --output VIRTUAL-1 --off \
  --output DP-1 --off\
  --output DP-2 --off\
  --output DP-3 --off\
  --output HDMI-1 --off\
  --output HDMI-3 --off\
  --output HDMI-2 --off\
  --output VGA-1 --off\
  --output LVDS-1 --pos 0x0 --mode 1366x768 --primary\
  && notify-send "On the move!" || notify-send "unable to undock :("
xset s 90
xset dpms 90 90 90
xset dpms force on
