#!/bin/sh
# TODO: make this work for things other than home dock or no screens
docked_displaycount=$(xrandr |grep -e 'HDMI-1 connected' |wc -l)

projector_displaycount=$(xrandr |grep -e 'MEME connected' |wc -l)

work_displaycount=$(xrandr |grep -e 'MEME connected' |wc -l)

if [ $projector_displaycount = 1 ] ; then
  display_comfy_projector
elif [ $work_displaycount = 1 ] ; then
  display_work
elif [ $docked_displaycount = 1 ] ; then
  display_home_dock
else
  display_standalone
fi
