#!/bin/sh

xrandr \
  --output HDMI-1 --primary --mode 1920x1080 --left-of eDP-1 --rotate normal \
  --output eDP-1 --mode 1366x768 --rotate normal\
  && notify-send "Docked!"|| notify-send "Unable to dock :("

xset s 0
xset dpms 0 0 0
xset dpms force on
remapkeyboard
i3-msg restart

