#!/bin/sh
xrandr \
  --output VIRTUAL-1 --off \
  --output DP-1-1 --off\
  --output DP-1-2 --off \
  --output DP-1-3 --off\
  --output HDMI-1 --off\
  --output DP-1 --off \
  --output DP-2 --off \
  --output eDP-1 --pos 0x0 --mode 1920x1080 --primary\
  && notify-send "On the move!" || notify-send "unable to undock :("

xset s 90
xset dpms 90 90 90
xset dpms force on
