#!/bin/zsh
xrandr --output VIRTUAL1 --off \
  --output DP1 --off\
  --output DP2 --off\
  --output DP3 --off\
  --output HDMI1 --off\
  --output HDMI3 --off\
  --output HDMI2 --off\
  --output VGA1 --off\
  --output LVDS1 --pos 0x0 --mode 1366x768 --primary\
  && notify-send "On the move!" || notify-send "unable to undock :("
xset s 90
xset dpms 90 90 90
xset dpms force on
remapkeyboard
