#!/bin/sh

xrandr \
  --output VGA1 --mode 1024x768 --same-as LVDS1\
  --output LVDS1 --mode 1024x768 --primary \
  --output DP3 --off \
  --output DP2 --off \
  --output DP1 --off \
  --output HDMI1 --off \
  --output HDMI2 --off \
  --output HDMI3 --off \
  && notify-send "Using projector!" || notify-send "Unable to use projector :("

xset s 0
xset dpms 0 0 0
xset dpms force on
remapkeyboard

