#!/bin/zsh

# TODO: projector and work dock modes

chosen=$(echo -e 'home-dock\nstandalone\ncomfy-projector\nhd-projector\nwork-dock' | dmenu -i -p "Select display arangement:") &&
case "$chosen" in
	"standalone") display_standalone ; exit ;;
	"home-dock") display_home_dock ;;
	"comfy-projector") display_comfy_projector ;;
	*) arandr;;
esac
