#!/bin/sh

# dependencies: ssh-askpass, keepassxc-cli and dmenu

db=~/syncthing/essential/Passwords.kdbx

CACHE=$HOME/.cache/dmenu-keepassxc
mkdir -p "$CACHE"

dbpass=$(ssh-askpass|tr -d '\n')
[ ! "$dbpass" ] && exit

entries=${CACHE}/tmp

echo "$dbpass"|keepassxc-cli ls "$db">"$entries" || { notify-send "Wrong password"; exit 1; }

entry=$(dmenu -l 20 -p "Secret for:"< "$entries")

if [ -z "$1" ] ; then
  field="$(echo "$dbpass" |keepassxc-cli show "$db" "$entry"|dmenu -l 20 -p "Field:" |grep -o '^[^:]*')"
  echo "$dbpass"|keepassxc-cli clip -a "$field" "$db" "$entry"|xargs -0 notify-send
elif [ "$1" = "TOPT" ] ; then 
  echo "$dbpass"|keepassxc-cli clip -t "$db" "$entry"|xargs -0 notify-send
else
  echo "$dbpass"|keepassxc-cli clip -a "$1" "$db" "$entry"|xargs -0 notify-send
fi

rm -r "$CACHE"
