#!/bin/zsh

# From arch wiki: 
# For enabling automatic profile switching from A2DP to HSP when a recording stream appears without any role set, you can append auto_switch=2 to load-module module-bluetooth-policy in /etc/pulse/default.pa
# ^ would make the last two commands kinda useless
# update, i don't like how auto_switch works
HEADSET_ADDR="94:DB:56:F0:11:D5"

HEADSET_CARD_INDEX=$(pactl list short cards \
  | grep $(echo ${HEADSET_ADDR}| sed s/:/_/g) \
  | cut -f 1)

if [ "$1" = "connect" ] ; then
  bluetoothctl -- power on
  bluetoothctl -- default-agent
  notify-send "$(bluetoothctl -- connect ${HEADSET_ADDR})"
elif [ "$1" = "disconnect" ] ; then
  notify-send "$(bluetoothctl -- disconnect ${HEADSET_ADDR})"
elif [ "$1" = "a2dp" ] ; then
  pacmd set-card-profile "${HEADSET_CARD_INDEX}" a2dp_sink \
    && notify-send "headset set as A2DP" \
    || notify-send "there was an error changing headset settings"
elif [ "$1" = "headset" ] ; then
  pacmd set-card-profile "${HEADSET_CARD_INDEX}" headset_head_unit \
    && notify-send "headset set as headset" \
    || notify-send "there was an error changing headset settings"
elif [ "$1" = "fixdaemon" ] ; then
  sudo systemctl stop bluetooth || notify send "there was a problem stopping bluetooth daemon"
  sudo modprobe -r btusb || notify send "there was a problem removing btusb module"
  sudo modprobe  btusb || notify send "there was a problem loading btusb module"
  sudo systemctl start bluetooth \
    && notify-send "daemon restarted" \
    || notify-send "there was a problem restarting the daemon"
else
  exit 1
fi

