#!/bin/zsh
xrandr --output DP-1 --off --output HDMI-1 --mode 2560x1080 --pos 1366x768 --rotate normal --output eDP-1 --primary --mode 1366x768 --pos 0x1080 --rotate normal --output HDMI-2 --off
i3-msg "restart"
