#!/bin/zsh
#usage: i3_tmux_dropdown session_name command.
#the session name is the same as the window title.
#underscores break it for some reason
ARGS=($@)
COMMAND=${ARGS[@]:1}
WORKING_DIR=${WORKING_DIR:-${HOME}}
SESSION_NAME="$1"

if ! xdotool search --name "${SESSION_NAME}";then
   st -t "$SESSION_NAME" -e tmux new-session -A -s "$1" -c "${WORKING_DIR}" ${COMMAND} &
   notify-send "Creating dropdown: ${SESSION_NAME}"
fi
