#!/bin/sh

MIRRORS_DIR=/var/www/html/mirrors

for i in $1 $(ls $MIRRORS_DIR |shuf) ; do
  wget --recursive  --level inf --adjust-extension --convert-link --page-requisites --no-parent -P "$MIRRORS_DIR" "$i"
done

