#!/bin/zsh

URL=${QUTE_URL}
SOCKET="${HOME}/.mpv/socket"

if [ -n "${VIDEO}" ] ; then
  # TODO: choose what to do with dmenu if there's an mpv instance running
  xdotool search --class mpv || { { pkill '^mpv$' ;  mpv --idle --ytdl-format="bestvideo[height<=?1080]+bestaudio/best" ; } & disown ; }
else
  pgrep '^mpv$' || mpv --no-video --idle & disown
fi

[ "$#" -eq 1 ] && URL="${1}"

while ! lsof "${SOCKET}"
do
  echo "waiting for mpv to start"
  sleep 1
done

if [ -n "${URL}" ] ; then
  mpvctl add "${URL}" \
  && notify-send "Added ${URL} to playlist"\
  || notify-send "Couldnt add ${URL} to playlist"
else
  exit 1
fi

