#!/bin/zsh

URL=${QUTE_URL}
SOCKET="${HOME}/.mpv/socket"

[ "$#" -eq 1 ] && URL="${1}"

if [ -n "${URL}" ] ; then
  if ! xdotool search --class mpv ; then
    pkill '^mpv$'
    mpv --ytdl-format="bestvideo[height<=?720]+bestaudio/best[height<=?720]" "${URL}" &
    while ! xdotool search --class mpv
    do
      echo "waiting for mpv to start"
      sleep 1
    done
  else
    mpvctl add "${URL}" \
    && notify-send "Added ${URL} to playlist"\
    || notify-send "Couldnt add ${URL} to playlist"
  fi
else
  exit 1
fi

