#!/bin/sh

reencode() {
  for i in $(ls ${1}/VID_*) ; do
    ffmpeg -n -i "$i" -c:v libx264 -crf 30 ~/phone/reenc/${i##*/} && echo would rm $i
  done
} 

adb pull /sdcard/DCIM ~/phone
adb pull /sdcard/OpenCamera ~/phone
adb pull /sdcard/Notes ~/phone
adb pull /sdcard/Pictures ~/phone
adb pull /sdcard/Recordings ~/phone
adb pull /sdcard/Movies ~/phone

adb shell rm -rf /sdcard/DCIM
adb shell rm -rf /sdcard/OpenCamera
adb shell rm -rf /sdcard/Movies

mkdir ~/phone/OpenCamera/reenc
reencode ~/phone/OpenCamera
reencode ~/phone/Movies

