#!/bin/sh

qutebrowser --target window -R "https://web.telegram.org/"
qutebrowser --target tab-bg-silent -R "https://web.whatsapp.com/" "https://app.slack.com/client/T0N639Z4N" "https://app.slack.com/client/T02536FCX/"
