#!/bin/sh

URL="$1"
if [ -z "$URL" ] ; then
  URL="$QUTE_URL"
fi

! echo "$URL" | grep "https*://\S\+\.[A-Za-z]\+\S*" >/dev/null &&
	notify-send "That doesn't look like a full URL." && exit
RSSFILE="${XDG_CONFIG_HOME:-$HOME/.config}/newsboat/urls"
if awk '{print $URL}' "$RSSFILE" | grep "^$URL$" >/dev/null; then
	notify-send "You already have this RSS feed."
else
	echo "$URL" >> "$RSSFILE" && notify-send "RSS feed added."
fi
