#!/bin/sh

tweetfile=~/notes/tweetlater.md

tweet="$(head -n 1 ${tweetfile})"

if /usr/local/bin/t update  "${tweet}" ; then
  echo "tweeted ${tweet} successfully"
  sed -i '1 d ' "${tweetfile}"
else
  echo "couldnt tweet ${tweet}"
fi
