#!/bin/zsh
xrandr --output VIRTUAL1 --off --output DP1 --off --output LVDS1 --pos 0x0 --mode 1366x768 --primary
setxkbmap -layout us -variant altgr-intl ; xmodmap ~/.Xmodmap
xset s 90
xset dpms 90 90 90
