#!/bin/sh
xrandr --output DP2 --off --output DP3 --primary --mode 2560x1080 --pos 1366x0 --rotate normal --output DP1 --off --output HDMI3 --off --output HDMI2 --off --output HDMI1 --off --output LVDS1 --mode 1366x768 --pos 2560x1080 --rotate normal --output VGA1 --off
xset s 0
xset dpms 0 0 0
i3-msg restart

