#!/bin/zsh
xrandr --output VIRTUAL1 --off --output DP1 --mode 2560x1080 --pos 0x0 --output LVDS1 --primary --mode 1366x768 --pos 554x1080
setxkbmap -layout us -variant altgr-intl ; xmodmap ~/.Xmodmap
xset s 0
xset dpms 0 0 0

