#!/bin/sh
xrandr --output DP-1 --off --output HDMI-1 --off --output eDP-1 --primary --mode 1366x768 --rotate normal --output HDMI-2 --off
setxkbmap -layout us -variant altgr-intl ; xmodmap ~/.Xmodmap
