#!/bin/sh

URL="$1"
if [ -z "$URL" ] ; then
  URL="$QUTE_URL"
else
  shift 1
fi

if [ -z "$URL" ] ; then
  exit 1
fi


FORMAT="bestvideo[height<=?720]+bestaudio/best[height<=?720]"
FLAGS="--add-metadata -ic --restrict-filenames"
VIDEOS_DESTINATION="${HOME}/youtube"

if [ -e "${VIDEOS_DESTINATION}/cookies.txt" ] ; then
  FLAGS="${FLAGS} --cookies ${VIDEOS_DESTINATION}/cookies.txt"
fi

# if [ -n "${LONG}" ] ; then
#   FLAGS="${FLAGS} --match-filter \"duration < 3600\""
# fi

youtube-dl ${FLAGS} -f "${FORMAT}" \
  -o "${VIDEOS_DESTINATION}/%(uploader)s/%(upload_date)s-%(title)s"\
  "${URL}"\
  "${@}"


