#!/bin/sh

URL="$1"
if [ -z "$URL" ] ; then
  URL="$QUTE_URL"
else
  shift 1
fi

if [ -z "$URL" ] ; then
  exit 1
fi

FORMAT="bestvideo[height<=?720]+bestaudio/best[height<=?720]"
FLAGS="--add-metadata -ic --restrict-filenames"
VIDEOS_DESTINATION="${HOME}/youtube"

youtube-dl ${FLAGS} -f "${FORMAT}" \
  --match-filter "duration < 3600"\
  -o "${VIDEOS_DESTINATION}/%(uploader)s/%(upload_date)s-%(title)s"\
  "${URL}"\
  "${@}"


