#!/bin/zsh

icon="⏹️"
playerstatus=""
title=""
if xdotool search --class mpv &>/dev/null ; then
  title="$(mpvctl title | sed  's/^[[:digit:]]*//')"
  if [ "$(mpvctl get-paused)" = "yes" ] ; then
    playerstatus="paused"
  else
    playerstatus="playing"
  fi
elif cmus-remote -Q &>/dev/null ; then
  playerstatus="$(cmus-remote -Q|head -n 1 |cut -d ' ' -f 2)" 
  title="$(cmus-remote -Q |grep 'tag title\b' | cut -f 3- -d ' ')"
else
  exit 0
fi
if [ "${playerstatus}" = "paused" ] ; then
  icon="⏸️"
elif [ "${playerstatus}" = "playing" ] ; then
  icon="▶️"
fi
#short & long text
echo ${icon} "$(echo -n ${title} | head -c 20)"
echo ${icon} "$(echo -n ${title} | head -c 20)"

# set a blueish color to show that the player is paused
if [ "${playerstatus}" != "playing" ] ; then
  echo '#2458a1'
fi
