#!/bin/sh

accounts="capu-tech personal-yandex fiuba-gmail work-gmail"
mail_count=""
for account in $accounts;
do
  mail_count="${mail_count}$(ls ~/mail/${account}/INBOX/new |wc -l)/"
done
#cut last / character
mail_count=$(echo ${mail_count}|head --bytes=-2)

echo "✉️: ${mail_count}"

echo "✉️:$(echo "${mail_count}"|tr '/' '+'|bc)"
