#!/bin/zsh

format_seconds(){
  minutes=$(($1 / 60))
  seconds=$(($1 % 60))
  echo -n "${minutes}:${seconds}"
}

icon="⏹️"
stopped="true"
# is mpv running?
if lsof "${MPV_SOCKET}" &>/dev/null ; then
  title=$(${HOME}/.scripts/mpvctl title) 
  if [ "$title" != null ] ;then
    stopped="false"
  fi
  paused=$(${HOME}/.scripts/mpvctl get-paused)
  if [ "${paused}" = "yes" ] ; then
    icon="⏸️"
  elif [ "${paused}" = "no" ] ; then
    icon="▶️"
  fi
fi
if [ "${stopped}" = true ] ;then
  exit 0
fi
playlist_position="[$(mpvctl get-playlist-index-1)/$(mpvctl get-playlist-length)]"

file_progress="$(format_seconds $(mpvctl get-progress-seconds))"
file_length="$(format_seconds $(mpvctl get-duration-seconds))"
file_position="(${file_progress}/${file_length})"

#long text
echo ${icon} ${title} ${playlist_position}${file_position}

#short text
echo ${icon} "$(echo -n ${title} | head -c 20)" ${playlist_position}

# set a blueish color to show that the player is paused
if [ "${paused}" = "yes" ] ; then
  echo '#2458a1'
fi

