#!/bin/zsh

icon="⏹️"
# is mpv running?
if lsof "${MPV_SOCKET}" &>/dev/null ; then
  paused=$(${HOME}/.scripts/mpvctl get_paused)
  if [ "${paused}" = "yes" ] ; then
    icon="⏸️"
  elif [ "${paused}" = "no" ] ; then
    icon="▶️"
  fi

  title=$(${HOME}/.scripts/mpvctl title) 
  if [ "$title" = null ] ;then
    icon="⏹️"
    title=""
  fi
fi

output="${icon} ${title}"
echo ${output}
# echo adds the newlines, and i don't want head to remove it
echo $(echo ${output} |head -c 28)

# set a blueish color to show that the player is paused
if [ "${paused}" = "yes" ] ; then
  echo '#2458a1'
fi
